config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end


  root :to => 'main#home'
  resources :remuneracions
  resources :empleados
  resources :proveedors
  resources :clientes
  resources :egresos
  resources :ingresos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/egreso.rb
class Egreso < ApplicationRecord
    belongs_to :proveedor

    paginates_per 10
end

app/controllers/egresos_controller.rb
class EgresosController < ApplicationController
  before_action :set_egreso, only: %i[ show edit update destroy ]

  # GET /egresos or /egresos.json
  def index
    @egresos = Egreso.page(params[:page])
    #@posts = Post.all.page()
  end

  # GET /egresos/1 or /egresos/1.json
  def show
  end

  # GET /egresos/new
  def new
    @egreso = Egreso.new
  end

  # GET /egresos/1/edit
  def edit
  end

  # POST /egresos or /egresos.json
  def create
    @egreso = Egreso.new(egreso_params)

    respond_to do |format|
      if @egreso.save
        format.html { redirect_to egreso_url(@egreso), notice: "Egreso was successfully created." }
        format.json { render :show, status: :created, location: @egreso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @egreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /egresos/1 or /egresos/1.json
  def update
    respond_to do |format|
      if @egreso.update(egreso_params)
        format.html { redirect_to egreso_url(@egreso), notice: "Egreso was successfully updated." }
        format.json { render :show, status: :ok, location: @egreso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @egreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /egresos/1 or /egresos/1.json
  def destroy
    @egreso.destroy

    respond_to do |format|
      format.html { redirect_to egresos_url, notice: "Egreso was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_egreso
      @egreso = Egreso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def egreso_params
      params.require(:egreso).permit(:documento, :nro_doc, :fecha_emision, :fecha_pago, :rut_proveedor, :monto_egreso, :tipo_egreso)
    end
end

app/helpers/egresos_helper.rb
module EgresosHelper
end

app/views/egresos/_egreso.html.erb
<div id="<%= dom_id egreso %>">
  
  <p>
    <strong>Documento:</strong>
    <%= egreso.documento %>
  </p>

  <p>
    <strong>Nro doc:</strong>
    <%= egreso.nro_doc %>
  </p>

  <p>
    <strong>Fecha emision:</strong>
    <%= egreso.fecha_emision %>
  </p>

  <p>
    <strong>Fecha pago:</strong>
    <%= egreso.fecha_pago %>
  </p>

  <p>
    <strong>Rut proveedor:</strong>
    <%= egreso.proveedor.rut_proveedor %>
  </p>

  <p>
    <strong>Monto egreso:</strong>
    <%= egreso.monto_egreso %>
  </p>

  <p>
    <strong>Tipo egreso:</strong>
    <%= egreso.tipo_egreso %>
  </p>
  
</div>

app/views/egresos/_form.html.erb
<%= form_with(model: egreso) do |form| %>
  <% if egreso.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(egreso.errors.count, "error") %> prohibited this egreso from being saved:</h2>

      <ul>
        <% egreso.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :documento, style: "display: block" %>
    <%= form.text_field :documento %>
  </div>

  <div>
    <%= form.label :nro_doc, style: "display: block" %>
    <%= form.number_field :nro_doc %>
  </div>

  <div>
    <%= form.label :fecha_emision, style: "display: block" %>
    <%= form.date_field :fecha_emision %>
  </div>

  <div>
    <%= form.label :fecha_pago, style: "display: block" %>
    <%= form.date_field :fecha_pago %>
  </div>

  <div>
    <%= form.label :rut_proveedor, style: "display: block" %>
    <%= form.text_field :rut_proveedor %>
  </div>

  <div>
    <%= form.label :monto_egreso, style: "display: block" %>
    <%= form.number_field :monto_egreso %>
  </div>

  <div>
    <%= form.label :tipo_egreso, style: "display: block" %>
    <%= form.text_field :tipo_egreso %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/egresos/edit.html.erb
<h1>Editing egreso</h1>

<%= render "form", egreso: @egreso %>

<br>

<div>
  <%= link_to "Show this egreso", @egreso %> |
  <%= link_to "Back to egresos", egresos_path %>
</div>

app/views/egresos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Egresos</h1>
<%= paginate @egresos%>
<%= link_to "New egreso", new_egreso_path %>
<div id="egresos">
  <% @egresos.each do |egreso| %>
    <%= render egreso %>
    <p>
      <%= link_to "Show this egreso", egreso %>
    </p>
  <% end %>
</div>

app/views/egresos/new.html.erb
<h1>New egreso</h1>

<%= render "form", egreso: @egreso %>

<br>

<div>
  <%= link_to "Back to egresos", egresos_path %>
</div>

app/views/egresos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @egreso %>

<div>
  <%= link_to "Edit this egreso", edit_egreso_path(@egreso) %> |
  <%= link_to "Back to egresos", egresos_path %>

  <%= button_to "Destroy this egreso", @egreso, method: :delete %>
</div>