config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end


  root :to => 'main#home'
  resources :remuneracions
  resources :empleados
  resources :proveedors
  resources :clientes
  resources :egresos
  resources :ingresos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ingreso.rb
class Ingreso < ApplicationRecord
    belongs_to :cliente
    paginates_per 10
end

app/controllers/ingresos_controller.rb
class IngresosController < ApplicationController
  before_action :set_ingreso, only: %i[ show edit update destroy ]

  # GET /ingresos or /ingresos.json
  def index
    @ingresos = Ingreso.page(params[:page])
  end

  # GET /ingresos/1 or /ingresos/1.json
  def show
  end

  # GET /ingresos/new
  def new
    @ingreso = Ingreso.new
  end

  # GET /ingresos/1/edit
  def edit
  end

  # POST /ingresos or /ingresos.json
  def create
    @ingreso = Ingreso.new(ingreso_params)

    respond_to do |format|
      if @ingreso.save
        format.html { redirect_to ingreso_url(@ingreso), notice: "Ingreso was successfully created." }
        format.json { render :show, status: :created, location: @ingreso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingresos/1 or /ingresos/1.json
  def update
    respond_to do |format|
      if @ingreso.update(ingreso_params)
        format.html { redirect_to ingreso_url(@ingreso), notice: "Ingreso was successfully updated." }
        format.json { render :show, status: :ok, location: @ingreso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingreso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingresos/1 or /ingresos/1.json
  def destroy
    @ingreso.destroy

    respond_to do |format|
      format.html { redirect_to ingresos_url, notice: "Ingreso was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingreso
      @ingreso = Ingreso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingreso_params
      params.require(:ingreso).permit(:documento, :nro_doc, :fecha_emision, :fecha_pago, :rut_cliente, :monto_ingreso, :tipo_ingreso)
    end
end

app/helpers/ingresos_helper.rb
module IngresosHelper
end

app/views/ingresos/_form.html.erb
<%= form_with(model: ingreso) do |form| %>
  <% if ingreso.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ingreso.errors.count, "error") %> prohibited this ingreso from being saved:</h2>

      <ul>
        <% ingreso.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :documento, style: "display: block" %>
    <%= form.text_field :documento %>
  </div>

  <div>
    <%= form.label :nro_doc, style: "display: block" %>
    <%= form.number_field :nro_doc %>
  </div>

  <div>
    <%= form.label :fecha_emision, style: "display: block" %>
    <%= form.date_field :fecha_emision %>
  </div>

  <div>
    <%= form.label :fecha_pago, style: "display: block" %>
    <%= form.date_field :fecha_pago %>
  </div>

  <div>
    <%= form.label :rut_cliente, style: "display: block" %>
    <%= form.text_field :rut_cliente %>
  </div>

  <div>
    <%= form.label :monto_ingreso, style: "display: block" %>
    <%= form.number_field :monto_ingreso %>
  </div>

  <div>
    <%= form.label :tipo_ingreso, style: "display: block" %>
    <%= form.text_field :tipo_ingreso %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ingresos/_ingreso.html.erb
<div id="<%= dom_id ingreso %>">
  <p>
    <strong>Documento:</strong>
    <%= ingreso.documento %>
  </p>

  <p>
    <strong>Nro doc:</strong>
    <%= ingreso.nro_doc %>
  </p>

  <p>
    <strong>Fecha emision:</strong>
    <%= ingreso.fecha_emision %>
  </p>

  <p>
    <strong>Fecha pago:</strong>
    <%= ingreso.fecha_pago %>
  </p>

  <p>
    <strong>Rut cliente:</strong>
    <%= ingreso.cliente.rut_cliente %>
  </p>

  <p>
    <strong>Monto ingreso:</strong>
    <%= ingreso.monto_ingreso %>
  </p>

  <p>
    <strong>Tipo ingreso:</strong>
    <%= ingreso.tipo_ingreso %>
  </p>

</div>

app/views/ingresos/edit.html.erb
<h1>Editing ingreso</h1>

<%= render "form", ingreso: @ingreso %>

<br>

<div>
  <%= link_to "Show this ingreso", @ingreso %> |
  <%= link_to "Back to ingresos", ingresos_path %>
</div>

app/views/ingresos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ingresos</h1>
<%= paginate @ingresos%>
<%= link_to "New ingreso", new_ingreso_path %>
<div id="ingresos">
  <% @ingresos.each do |ingreso| %>
    <%= render ingreso %>
    <p>
      <%= link_to "Show this ingreso", ingreso %>
    </p>
  <% end %>
</div>

app/views/ingresos/new.html.erb
<h1>New ingreso</h1>

<%= render "form", ingreso: @ingreso %>

<br>

<div>
  <%= link_to "Back to ingresos", ingresos_path %>
</div>

app/views/ingresos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ingreso %>

<div>
  <%= link_to "Edit this ingreso", edit_ingreso_path(@ingreso) %> |
  <%= link_to "Back to ingresos", ingresos_path %>

  <%= button_to "Destroy this ingreso", @ingreso, method: :delete %>
</div>