config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end


  root :to => 'main#home'
  resources :remuneracions
  resources :empleados
  resources :proveedors
  resources :clientes
  resources :egresos
  resources :ingresos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/empleado.rb
class Empleado < ApplicationRecord
    has_many :remuneracions
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: %i[ show edit update destroy ]

  # GET /empleados or /empleados.json
  def index
    @empleados = Empleado.page(params[:page])
  end

  # GET /empleados/1 or /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados or /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)

    respond_to do |format|
      if @empleado.save
        format.html { redirect_to empleado_url(@empleado), notice: "Empleado was successfully created." }
        format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1 or /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to empleado_url(@empleado), notice: "Empleado was successfully updated." }
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1 or /empleados/1.json
  def destroy
    @empleado.destroy

    respond_to do |format|
      format.html { redirect_to empleados_url, notice: "Empleado was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def empleado_params
      params.require(:empleado).permit(:rut_empleado, :nombre_empleado, :apellido_empleado, :tipo_empleado)
    end
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/empleados/_empleado.html.erb
<div id="<%= dom_id empleado %>">
  <p>
    <strong>Rut empleado:</strong>
    <%= empleado.rut_empleado %>
  </p>

  <p>
    <strong>Nombre empleado:</strong>
    <%= empleado.nombre_empleado %>
  </p>

 <!-- <p>
    <strong>Apellido empleado:</strong>
    <%= empleado.apellido_empleado %>
  </p> -->

  <p>
    <strong>Tipo empleado:</strong>
    <%= empleado.tipo_empleado %>
  </p>

</div>

app/views/empleados/_form.html.erb
<%= form_with(model: empleado) do |form| %>
  <% if empleado.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(empleado.errors.count, "error") %> prohibited this empleado from being saved:</h2>

      <ul>
        <% empleado.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :rut_empleado, style: "display: block" %>
    <%= form.text_field :rut_empleado %>
  </div>

  <div>
    <%= form.label :nombre_empleado, style: "display: block" %>
    <%= form.text_field :nombre_empleado %>
  </div>

  <div>
    <%= form.label :apellido_empleado, style: "display: block" %>
    <%= form.text_field :apellido_empleado %>
  </div>

  <div>
    <%= form.label :tipo_empleado, style: "display: block" %>
    <%= form.text_field :tipo_empleado %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/empleados/edit.html.erb
<h1>Editing empleado</h1>

<%= render "form", empleado: @empleado %>

<br>

<div>
  <%= link_to "Show this empleado", @empleado %> |
  <%= link_to "Back to empleados", empleados_path %>
</div>

app/views/empleados/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Empleados</h1>
<%= paginate @empleados%>
<%= link_to "New empleado", new_empleado_path %>
<div id="empleados">
  <% @empleados.each do |empleado| %>
    <%= render empleado %>
    <p>
      <%= link_to "Show this empleado", empleado %>
    </p>
  <% end %>
</div>

app/views/empleados/new.html.erb
<h1>New empleado</h1>

<%= render "form", empleado: @empleado %>

<br>

<div>
  <%= link_to "Back to empleados", empleados_path %>
</div>

app/views/empleados/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @empleado %>

<div>
  <%= link_to "Edit this empleado", edit_empleado_path(@empleado) %> |
  <%= link_to "Back to empleados", empleados_path %>

  <%= button_to "Destroy this empleado", @empleado, method: :delete %>
</div>